{% set name = "pyimagej" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 523dd9a9a52639e786fc8639a028131ddcbdfacf7f89609f1df96b7dd784f61c

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . -vvv  --no-deps"
  skip: True  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyjnius
    - imglyb
    - matplotlib

test:
  imports:
    - imagej

about:
  home: https://github.com/imagej/pyimagej
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  summary: 'Supercharged Java access from Python.'
  doc_url: https://github.com/imagej/pyimagej
  dev_url: https://github.com/imagej/pyimagej

extra:
  recipe-maintainers:
    - ctrueden
    - hadim
